  (defun weejud-theme ()
  (interactive)
  (color-theme-install
   '(weejud-theme
      ((background-color . "#fdfdfc")
      (background-mode . light)
      (border-color . "#e6ffef")
      (cursor-color . "#c6cdc9")
      (foreground-color . "#08365e")
      (mouse-color . "black"))
     (fringe ((t (:background "#e6ffef"))))
     (mode-line ((t (:foreground "#ffffff" :background "#595959"))))
     (region ((t (:background "#cff0fc"))))
     (font-lock-builtin-face ((t (:foreground "#f155cf"))))
     (font-lock-comment-face ((t (:foreground "#b2b5c2"))))
     (font-lock-function-name-face ((t (:foreground "#7bd10a"))))
     (font-lock-keyword-face ((t (:foreground "#20a4f8"))))
     (font-lock-string-face ((t (:foreground "#8d8ea5"))))
     (font-lock-type-face ((t (:foreground"#e70d2c"))))
     (font-lock-constant-face ((t (:foreground "#c9b408"))))
     (font-lock-variable-name-face ((t (:foreground "#e6a00f"))))
     (minibuffer-prompt ((t (:foreground "#7299ff" :bold t))))
     (font-lock-warning-face ((t (:foreground "red" :bold t))))
     )))
(provide 'weejud-theme)
